const date = {
    gorilla: {
        title: 'Gorilla camera',
        subtitle: 'Western Lowland Gorilla',
        imageBotton: '../../assets/imeges/zoos/garillaBotton.png',
        video: ['https://www.youtube.com/embed/ODyB9i6bGwQ', 'https://www.youtube.com/embed/wDECqJsiGqw', 'https://www.youtube.com/embed/cf1Pw3WIb4w', 'https://www.youtube.com/embed/4bxwB4jD_Eg'],
        photoFromVideo: ['../../assets/imeges/zoos/garillaForSlider-0.jpg', '../../assets/imeges/zoos//garillaForSlider-1.jpg', '../../assets/imeges/zoos//garillaForSlider-2.jpg', '../../assets/imeges/zoos//garillaForSlider-3.jpg',],
        briefImage: '../../assets/imeges/zoos/garillaBref.png',
        briefText: 'Giant pandas are very unusual animals that eat almost exclusively bamboo, which is very low in nutrients. Because of this, they have many unique adaptations for their low-energy lifestyle. Giant pandas are solitary, with males and females coming together only briefly to mate. Habitat loss is the primary threat to this species. Its popularity around the world has helped the giant panda become the focus of successful conservation programs.',
        text: [
            ['Diet:', 'Herbivore (We provide a medley of fruits and vegetables to our western lowland gorillas)'],
            ['Range: ', 'Western Africa [VIEW MAP]'],
            ['Habitat: ', 'Rainforests (Simulation of the natural environment)'],
            ['General Information: ', '', 'There are two species of gorilla, each containing two subspecies. The two species are eastern and western, and the four sub-species are Cross River and Western Lowland (are sub-species of the Western species) and Grauer’s and Mountain (are sub-species of the Eastern species). Western gorillas can be distinguished from other gorilla subspecies by their brownish-gray hair, auburn-colored crests and overall smaller size. Eastern gorillas tend to be black in color and larger in size. In all gorillas, males develop silver coloration along their backs as they mature. The species is diurnal, which means they are active during the day, and of all the great apes, gorillas are the most terrestrial. This means that they primarily live on the ground, although they do occasionally climb trees to feed and nest. They are also able to stand on two legs for short periods of time.'],
            ['Physical features and characteristics:', 'Gorillas are the largest of all primates and reach physical maturity between 12 and 15 years of age. Males can be between 350 and 450 pounds, almost twice as much as females, weighing in between 150 and 250 pounds. Males stand between 5.5 to 6 feet tall. Females are a bit smaller, standing between 4’7” to 4’11”. The males’ heads are large and pointed due to the sagittal crest that forms the back of the top of the head. This crest serves as the foundation for attachment of a great number of jaw muscle fibers, which allows for the chewing power needed to process tough vegetation.', 'The vision and perception of western lowland gorillas is similar to that of humans. Gorillas have a prominent brow ridge, small, flat ears, and hear about the same as humans. The nose is broad, flat and fleshy. The wrinkles on a gorilla’s nose, known as a noseprint, are like human fingerprints, and every individual’s noseprint is unique. Researchers use these noseprints as identification markers in their studies, both in zoological settings and in the wild.', 'Gorillas have 32 teeth, including sharp canines used for defense and breaking through vegetation. Their molars have complicated patterns of cups and ridges that facilitate chewing of tough plant fibers.', 'Gorillas’ faces, hands, and feet are bare, but the rest of their bodies are covered with short, thin hair. Gorilla hands and feet are large, with leathery palms and soles, and broad, flat nails Their hands are very dexterous and can pick up small, delicate objects. Like their hands, their feet have opposable thumbs and toes. Like all apes, gorillas’ arms are longer than their legs—a feature that allows them to walk on all fours. They are called “knuckle-walkers,” meaning that they walk on the knuckles of their forelimbs and the soles of their hind limbs. This form of locomotion develops calluses on the knuckles, preserving the sensitivity of the fingertips necessary for manipulating smaller objects.'],
            ['Lifestyle and reproduction:', `Gorillas tend to be shy, peaceful creatures; they are not normally aggressive to other animals unless provoked. However, if they are provoked, they can be dangerous. They can demonstrate aggression by charging towards perceived intruders. Typically, they will not actually hit the intruder, but rush past, turn and then charge again.','Gorillas use a combination of vocalizations, visual signals and scents to communicate. They are considered relatively quiet compared to other primates, but do have at least 25 recognized vocalizations, including:
        <br> -Hooting: Can carry for a mile through the forest and is usually accompanied by display behavior such as chest beating, strutting, and vegetation slapping
        <br> -Screams: Sounds of alarm or warning
        <br> -Belches: Deep rumblings of contentment, comfort, or well-being
        <br> -Sharp Grunts: Used when discipline is required
        <br> -Whoop Barks: High-pitched barks denote curiosity
        <br> -Bark Grunt: Aggression
        <br> -Chuckles: Playfulness`,
                'Infants have three distinct vocalizations; these are similar to the cries of a human baby. They will typically cry when hurt or frightened, resulting in an immediate response from the mother.', 'Dominant males also have a distinctive smell that they use to communicate with other troops and to maintain contact with their own troop. Perhaps the most recognizable behavior performed by gorillas is chest-beating. It is primarily done by male gorillas at the end of a display meant to intimidate intruding males or predators. The sound can be heard for long distances. Females will chest-beat infrequently; they will typically beat their hands against the insides of their thighs. Chest-beating can also indicate playful behavior, however, especially in the young. Young gorillas play much like humans do, playing tag and doing somersaults.', 'Western lowland gorillas live in family groups known as troops. These troops can consist of 5 to 30 individuals, although the average size is 11. The group is led by a dominant silverback male and contains several adult females and their young. The females will typically bond with the silverback, but not necessarily with each other. The silverback will remain dominant for as long as he can defeat competing males.', 'There are several younger, blackback males that remain in the group until they are capable of challenging the silverback. These young males are often driven out of the troop to live a solitary life or to live in a smaller group with other bachelors until they establish their own troops. If a dominant silverback is displaced, the new dominant male will typically kill the infants in the troop, sending the females prematurely into reproductive cycling. This increases the male’s chances of siring offspring, as his time as the dominant male is uncertain. As such, females consider a male’s ability to fight paramount to their offspring’s survival.', 'On maturing, females will also leave their natal group to join a lone male or another small group. This is vital to prevent inbreeding and to protect the gene pool.',
                `Nesting typically occurs in the late afternoon, with the gorillas bedding down for the night at sundown. The females and their offspring will build nests of leaves and branches, while the dominant silverback will settle at the base of the tree, in order to protect his family. At Zoo Atlanta, while the gorillas are outside, their indoor areas are thoroughly cleaned; the walls and floors are scrubbed with disinfectant. The gorillas are offered hay in their indoor area at night and nest with this material, replicating natural behavior.`,
                `In a troop, the single silverback male will mate with the females, siring all the offspring of the troop. Females generally reach reproductive maturity between 7 and 8 years of age, with males reaching maturity later, around 10 years of age, due to competition. The potential breeding season is year-round and gestation typically takes 256 days, or about 8.5 months. Labor can last anywhere from one to 4 hours. Babies are usually born singly; twins are rare. Newborns weigh between 3 and 5 pounds and are weaned around 2 to 3 years of age, but can be dependent on their mothers for up to 4 years. The average interval between births for a female gorilla is four to six years.`,
            ],
            ['Habitat:', 'Western lowland gorillas prefer the tall, lush tropical forest of west and central Africa. The herbs, shrubs and vines that make up its diet grow best where the open canopy allows plenty of light to reach the forest floor. These tropical forests also contain a much higher diversity of arboreal substrates and foods, in particular fruit, than mountainous habitats. Western lowland gorillas live primarily on the ground and build sleeping nests on the ground or in the trees for the night.'],
            ['Diet:', 'Western lowland gorillas are primarily herbivorous, feeding on plant parts including seeds, leaves, stems, shoots, roots and flowers; however, they prefer fruit whenever it’s in season. Occasionally they will eat insects, such as termites or ants, as a supplement to their diet when they are readily available. Due to their dietary preferences, western lowland gorillas spend a lot of their time in and around trees, especially fruit trees. Even large males can sometimes be found up in the trees, but they are careful to stay near a main trunk or on larger branches that are able to support their weight. Younger, lighter gorillas may climb higher in trees, even swinging freely from branch to branch. Gorillas never completely strip vegetation from a single area; rather, the rapid regrowth of the vegetation they consume allows them to stay within a reasonable confined home range for extended periods of time.', 'Here at Zoo, we provide a medley of fruits and vegetables to our western lowland gorillas. These include apples, oranges, bananas, raisins, sweet potatoes, cabbage, collards, and primate chow. In the morning, vegetables and fruit are chopped up and scattered around the habitat. From there, the gorillas come outside and forage for their food as they would in the wild. Browse foods including bamboo, banana leaves, mulberry, elm and willow are also scattered in their habitat.']
        ]
    },
    alligator: {
        title: 'Alligator camera',
        subtitle: 'Alligator',
        imageBotton: '../../assets/imeges/zoos/alligatorBotton.png',
        video: ['https://www.youtube.com/embed/X5Im4mMFK4A', 'https://www.youtube.com/embed/SlLuC7257pc', 'https://www.youtube.com/embed/_bVZeOt7bCw', 'https://www.youtube.com/embed/Sm9oYDVWZY4'],
        photoFromVideo: ['../../assets/imeges/zoos//alligatorForSlider-0.jpg', '../../assets/imeges/zoos//alligatorForSlider-1.jpg', '../../assets/imeges/zoos//alligatorForSlider-2.jpg', '../../assets/imeges/zoos//alligatorForSlider-3.jpg',],
        briefImage: '../../assets/imeges/zoos/alligatorBref.png',
        briefText: `Alligators differ from other members of the crocodile family in having a wider snout; their eyes are more dorsal (at the top of the head). Large alligators' eyes glow red; small alligators' eyes glow green. Alligators can be spotted in the dark by this sign.`,
        text: [
            ['Diet:', 'Herbivore (We provide a medley of fruits and vegetables to our western lowland gorillas)'],
            ['Range: ', 'Western Africa'],
            ['Habitat: ', 'Rainforests (Simulation of the natural environment)'],
            ['General Information: ', '', 'There are two species of gorilla, each containing two subspecies. The two species are eastern and western, and the four sub-species are Cross River and Western Lowland (are sub-species of the Western species) and Grauer’s and Mountain (are sub-species of the Eastern species). Western gorillas can be distinguished from other gorilla subspecies by their brownish-gray hair, auburn-colored crests and overall smaller size. Eastern gorillas tend to be black in color and larger in size. In all gorillas, males develop silver coloration along their backs as they mature. The species is diurnal, which means they are active during the day, and of all the great apes, gorillas are the most terrestrial. This means that they primarily live on the ground, although they do occasionally climb trees to feed and nest. They are also able to stand on two legs for short periods of time.'],
            ['Physical features and characteristics:', 'Gorillas are the largest of all primates and reach physical maturity between 12 and 15 years of age. Males can be between 350 and 450 pounds, almost twice as much as females, weighing in between 150 and 250 pounds. Males stand between 5.5 to 6 feet tall. Females are a bit smaller, standing between 4’7” to 4’11”. The males’ heads are large and pointed due to the sagittal crest that forms the back of the top of the head. This crest serves as the foundation for attachment of a great number of jaw muscle fibers, which allows for the chewing power needed to process tough vegetation.', 'The vision and perception of western lowland gorillas is similar to that of humans. Gorillas have a prominent brow ridge, small, flat ears, and hear about the same as humans. The nose is broad, flat and fleshy. The wrinkles on a gorilla’s nose, known as a noseprint, are like human fingerprints, and every individual’s noseprint is unique. Researchers use these noseprints as identification markers in their studies, both in zoological settings and in the wild.', 'Gorillas have 32 teeth, including sharp canines used for defense and breaking through vegetation. Their molars have complicated patterns of cups and ridges that facilitate chewing of tough plant fibers.', 'Gorillas’ faces, hands, and feet are bare, but the rest of their bodies are covered with short, thin hair. Gorilla hands and feet are large, with leathery palms and soles, and broad, flat nails Their hands are very dexterous and can pick up small, delicate objects. Like their hands, their feet have opposable thumbs and toes. Like all apes, gorillas’ arms are longer than their legs—a feature that allows them to walk on all fours. They are called “knuckle-walkers,” meaning that they walk on the knuckles of their forelimbs and the soles of their hind limbs. This form of locomotion develops calluses on the knuckles, preserving the sensitivity of the fingertips necessary for manipulating smaller objects.'],
            ['Lifestyle and reproduction:', `Gorillas tend to be shy, peaceful creatures; they are not normally aggressive to other animals unless provoked. However, if they are provoked, they can be dangerous. They can demonstrate aggression by charging towards perceived intruders. Typically, they will not actually hit the intruder, but rush past, turn and then charge again.','Gorillas use a combination of vocalizations, visual signals and scents to communicate. They are considered relatively quiet compared to other primates, but do have at least 25 recognized vocalizations, including:
        <br> -Hooting: Can carry for a mile through the forest and is usually accompanied by display behavior such as chest beating, strutting, and vegetation slapping
        <br> -Screams: Sounds of alarm or warning
        <br> -Belches: Deep rumblings of contentment, comfort, or well-being
        <br> -Sharp Grunts: Used when discipline is required
        <br> -Whoop Barks: High-pitched barks denote curiosity
        <br> -Bark Grunt: Aggression
        <br> -Chuckles: Playfulness`,
                'Infants have three distinct vocalizations; these are similar to the cries of a human baby. They will typically cry when hurt or frightened, resulting in an immediate response from the mother.', 'Dominant males also have a distinctive smell that they use to communicate with other troops and to maintain contact with their own troop. Perhaps the most recognizable behavior performed by gorillas is chest-beating. It is primarily done by male gorillas at the end of a display meant to intimidate intruding males or predators. The sound can be heard for long distances. Females will chest-beat infrequently; they will typically beat their hands against the insides of their thighs. Chest-beating can also indicate playful behavior, however, especially in the young. Young gorillas play much like humans do, playing tag and doing somersaults.', 'Western lowland gorillas live in family groups known as troops. These troops can consist of 5 to 30 individuals, although the average size is 11. The group is led by a dominant silverback male and contains several adult females and their young. The females will typically bond with the silverback, but not necessarily with each other. The silverback will remain dominant for as long as he can defeat competing males.', 'There are several younger, blackback males that remain in the group until they are capable of challenging the silverback. These young males are often driven out of the troop to live a solitary life or to live in a smaller group with other bachelors until they establish their own troops. If a dominant silverback is displaced, the new dominant male will typically kill the infants in the troop, sending the females prematurely into reproductive cycling. This increases the male’s chances of siring offspring, as his time as the dominant male is uncertain. As such, females consider a male’s ability to fight paramount to their offspring’s survival.', 'On maturing, females will also leave their natal group to join a lone male or another small group. This is vital to prevent inbreeding and to protect the gene pool.',
                `Nesting typically occurs in the late afternoon, with the gorillas bedding down for the night at sundown. The females and their offspring will build nests of leaves and branches, while the dominant silverback will settle at the base of the tree, in order to protect his family. At Zoo Atlanta, while the gorillas are outside, their indoor areas are thoroughly cleaned; the walls and floors are scrubbed with disinfectant. The gorillas are offered hay in their indoor area at night and nest with this material, replicating natural behavior.`,
                `In a troop, the single silverback male will mate with the females, siring all the offspring of the troop. Females generally reach reproductive maturity between 7 and 8 years of age, with males reaching maturity later, around 10 years of age, due to competition. The potential breeding season is year-round and gestation typically takes 256 days, or about 8.5 months. Labor can last anywhere from one to 4 hours. Babies are usually born singly; twins are rare. Newborns weigh between 3 and 5 pounds and are weaned around 2 to 3 years of age, but can be dependent on their mothers for up to 4 years. The average interval between births for a female gorilla is four to six years.`,
            ],
            ['Habitat:', 'Western lowland gorillas prefer the tall, lush tropical forest of west and central Africa. The herbs, shrubs and vines that make up its diet grow best where the open canopy allows plenty of light to reach the forest floor. These tropical forests also contain a much higher diversity of arboreal substrates and foods, in particular fruit, than mountainous habitats. Western lowland gorillas live primarily on the ground and build sleeping nests on the ground or in the trees for the night.'],
            ['Diet:', 'Western lowland gorillas are primarily herbivorous, feeding on plant parts including seeds, leaves, stems, shoots, roots and flowers; however, they prefer fruit whenever it’s in season. Occasionally they will eat insects, such as termites or ants, as a supplement to their diet when they are readily available. Due to their dietary preferences, western lowland gorillas spend a lot of their time in and around trees, especially fruit trees. Even large males can sometimes be found up in the trees, but they are careful to stay near a main trunk or on larger branches that are able to support their weight. Younger, lighter gorillas may climb higher in trees, even swinging freely from branch to branch. Gorillas never completely strip vegetation from a single area; rather, the rapid regrowth of the vegetation they consume allows them to stay within a reasonable confined home range for extended periods of time.', 'Here at Zoo, we provide a medley of fruits and vegetables to our western lowland gorillas. These include apples, oranges, bananas, raisins, sweet potatoes, cabbage, collards, and primate chow. In the morning, vegetables and fruit are chopped up and scattered around the habitat. From there, the gorillas come outside and forage for their food as they would in the wild. Browse foods including bamboo, banana leaves, mulberry, elm and willow are also scattered in their habitat.']
        ]
    },
    panda: {
        title: 'Panda camera',
        subtitle: 'Giant Panda',
        imageBotton: '../../assets/imeges/zoos/pandaBotton.png',
        video: ['https://www.youtube.com/embed/YdP2fFyjBWQ', 'https://www.youtube.com/embed/5-gHTvVB4RM', 'https://www.youtube.com/embed/unKI78hW6LI', 'https://www.youtube.com/embed/vcz7_PZyT-A'],
        photoFromVideo: ['../../assets/imeges/zoos//pandaForSlider-0.jpg', '../../assets/imeges/zoos//pandaForSlider-1.jpg', '../../assets/imeges/zoos//pandaForSlider-2.jpg', '../../assets/imeges/zoos//pandaForSlider-3.jpg',],
        briefImage: '../../assets/imeges/zoos/pandaBref.png',
        briefText: 'Giant pandas are very unusual animals that eat almost exclusively bamboo, which is very low in nutrients. Because of this, they have many unique adaptations for their low-energy lifestyle. Giant pandas are solitary, with males and females coming together only briefly to mate. Habitat loss is the primary threat to this species. Its popularity around the world has helped the giant panda become the focus of successful conservation programs.',
        text: [
            ['Diet:', 'Herbivore (We provide a medley of fruits and vegetables to our western lowland gorillas)'],
            ['Range: ', 'Western Africa'],
            ['Habitat: ', 'Rainforests (Simulation of the natural environment)'],
            ['General Information: ', '', 'There are two species of gorilla, each containing two subspecies. The two species are eastern and western, and the four sub-species are Cross River and Western Lowland (are sub-species of the Western species) and Grauer’s and Mountain (are sub-species of the Eastern species). Western gorillas can be distinguished from other gorilla subspecies by their brownish-gray hair, auburn-colored crests and overall smaller size. Eastern gorillas tend to be black in color and larger in size. In all gorillas, males develop silver coloration along their backs as they mature. The species is diurnal, which means they are active during the day, and of all the great apes, gorillas are the most terrestrial. This means that they primarily live on the ground, although they do occasionally climb trees to feed and nest. They are also able to stand on two legs for short periods of time.'],
            ['Physical features and characteristics:', 'Gorillas are the largest of all primates and reach physical maturity between 12 and 15 years of age. Males can be between 350 and 450 pounds, almost twice as much as females, weighing in between 150 and 250 pounds. Males stand between 5.5 to 6 feet tall. Females are a bit smaller, standing between 4’7” to 4’11”. The males’ heads are large and pointed due to the sagittal crest that forms the back of the top of the head. This crest serves as the foundation for attachment of a great number of jaw muscle fibers, which allows for the chewing power needed to process tough vegetation.', 'The vision and perception of western lowland gorillas is similar to that of humans. Gorillas have a prominent brow ridge, small, flat ears, and hear about the same as humans. The nose is broad, flat and fleshy. The wrinkles on a gorilla’s nose, known as a noseprint, are like human fingerprints, and every individual’s noseprint is unique. Researchers use these noseprints as identification markers in their studies, both in zoological settings and in the wild.', 'Gorillas have 32 teeth, including sharp canines used for defense and breaking through vegetation. Their molars have complicated patterns of cups and ridges that facilitate chewing of tough plant fibers.', 'Gorillas’ faces, hands, and feet are bare, but the rest of their bodies are covered with short, thin hair. Gorilla hands and feet are large, with leathery palms and soles, and broad, flat nails Their hands are very dexterous and can pick up small, delicate objects. Like their hands, their feet have opposable thumbs and toes. Like all apes, gorillas’ arms are longer than their legs—a feature that allows them to walk on all fours. They are called “knuckle-walkers,” meaning that they walk on the knuckles of their forelimbs and the soles of their hind limbs. This form of locomotion develops calluses on the knuckles, preserving the sensitivity of the fingertips necessary for manipulating smaller objects.'],
            ['Lifestyle and reproduction:', `Gorillas tend to be shy, peaceful creatures; they are not normally aggressive to other animals unless provoked. However, if they are provoked, they can be dangerous. They can demonstrate aggression by charging towards perceived intruders. Typically, they will not actually hit the intruder, but rush past, turn and then charge again.','Gorillas use a combination of vocalizations, visual signals and scents to communicate. They are considered relatively quiet compared to other primates, but do have at least 25 recognized vocalizations, including:
        <br> -Hooting: Can carry for a mile through the forest and is usually accompanied by display behavior such as chest beating, strutting, and vegetation slapping
        <br> -Screams: Sounds of alarm or warning
        <br> -Belches: Deep rumblings of contentment, comfort, or well-being
        <br> -Sharp Grunts: Used when discipline is required
        <br> -Whoop Barks: High-pitched barks denote curiosity
        <br> -Bark Grunt: Aggression
        <br> -Chuckles: Playfulness`,
                'Infants have three distinct vocalizations; these are similar to the cries of a human baby. They will typically cry when hurt or frightened, resulting in an immediate response from the mother.', 'Dominant males also have a distinctive smell that they use to communicate with other troops and to maintain contact with their own troop. Perhaps the most recognizable behavior performed by gorillas is chest-beating. It is primarily done by male gorillas at the end of a display meant to intimidate intruding males or predators. The sound can be heard for long distances. Females will chest-beat infrequently; they will typically beat their hands against the insides of their thighs. Chest-beating can also indicate playful behavior, however, especially in the young. Young gorillas play much like humans do, playing tag and doing somersaults.', 'Western lowland gorillas live in family groups known as troops. These troops can consist of 5 to 30 individuals, although the average size is 11. The group is led by a dominant silverback male and contains several adult females and their young. The females will typically bond with the silverback, but not necessarily with each other. The silverback will remain dominant for as long as he can defeat competing males.', 'There are several younger, blackback males that remain in the group until they are capable of challenging the silverback. These young males are often driven out of the troop to live a solitary life or to live in a smaller group with other bachelors until they establish their own troops. If a dominant silverback is displaced, the new dominant male will typically kill the infants in the troop, sending the females prematurely into reproductive cycling. This increases the male’s chances of siring offspring, as his time as the dominant male is uncertain. As such, females consider a male’s ability to fight paramount to their offspring’s survival.', 'On maturing, females will also leave their natal group to join a lone male or another small group. This is vital to prevent inbreeding and to protect the gene pool.',
                `Nesting typically occurs in the late afternoon, with the gorillas bedding down for the night at sundown. The females and their offspring will build nests of leaves and branches, while the dominant silverback will settle at the base of the tree, in order to protect his family. At Zoo Atlanta, while the gorillas are outside, their indoor areas are thoroughly cleaned; the walls and floors are scrubbed with disinfectant. The gorillas are offered hay in their indoor area at night and nest with this material, replicating natural behavior.`,
                `In a troop, the single silverback male will mate with the females, siring all the offspring of the troop. Females generally reach reproductive maturity between 7 and 8 years of age, with males reaching maturity later, around 10 years of age, due to competition. The potential breeding season is year-round and gestation typically takes 256 days, or about 8.5 months. Labor can last anywhere from one to 4 hours. Babies are usually born singly; twins are rare. Newborns weigh between 3 and 5 pounds and are weaned around 2 to 3 years of age, but can be dependent on their mothers for up to 4 years. The average interval between births for a female gorilla is four to six years.`,
            ],
            ['Habitat:', 'Western lowland gorillas prefer the tall, lush tropical forest of west and central Africa. The herbs, shrubs and vines that make up its diet grow best where the open canopy allows plenty of light to reach the forest floor. These tropical forests also contain a much higher diversity of arboreal substrates and foods, in particular fruit, than mountainous habitats. Western lowland gorillas live primarily on the ground and build sleeping nests on the ground or in the trees for the night.'],
            ['Diet:', 'Western lowland gorillas are primarily herbivorous, feeding on plant parts including seeds, leaves, stems, shoots, roots and flowers; however, they prefer fruit whenever it’s in season. Occasionally they will eat insects, such as termites or ants, as a supplement to their diet when they are readily available. Due to their dietary preferences, western lowland gorillas spend a lot of their time in and around trees, especially fruit trees. Even large males can sometimes be found up in the trees, but they are careful to stay near a main trunk or on larger branches that are able to support their weight. Younger, lighter gorillas may climb higher in trees, even swinging freely from branch to branch. Gorillas never completely strip vegetation from a single area; rather, the rapid regrowth of the vegetation they consume allows them to stay within a reasonable confined home range for extended periods of time.', 'Here at Zoo, we provide a medley of fruits and vegetables to our western lowland gorillas. These include apples, oranges, bananas, raisins, sweet potatoes, cabbage, collards, and primate chow. In the morning, vegetables and fruit are chopped up and scattered around the habitat. From there, the gorillas come outside and forage for their food as they would in the wild. Browse foods including bamboo, banana leaves, mulberry, elm and willow are also scattered in their habitat.']
        ]
    },
    eagle: {
        title: 'Eagle camera',
        subtitle: 'Eagle',
        imageBotton: '../../assets/imeges/zoos/eagleBotton.png',
        video: ['https://www.youtube.com/embed/DW-BSDZ7iqc', 'https://www.youtube.com/embed/A6H2ZdrKmzc', 'https://www.youtube.com/embed/eN4Qy5RRpsc', 'https://www.youtube.com/embed/RILkBqPVSEY'],
        photoFromVideo: ['../../assets/imeges/zoos//eagleForSlider-0.jpg', '../../assets/imeges/zoos//eagleForSlider-1.jpg', '../../assets/imeges/zoos//eagleForSlider-2.jpg', '../../assets/imeges/zoos//eagleForSlider-3.jpg',],
        briefImage: '../../assets/imeges/zoos/eagleBref.png',
        briefText: 'There are about 40 species of these birds in the world. The largest eagle is the Golden Eagle. It reaches a length of 95 cm and a wingspan of over two meters. Its plumage ranges from golden to t. brown. They nest exclusively in mountainous areas. They hunt in pairs and mainly during daylight hours. They feed on birds, squirrels, martens, hares and even larger animals.',
        text: [
            ['Diet:', 'Carnivore (Fish, lizards, snakes, mice)'],
            ['Range:', 'Eurasia and Africa [VIEW MAP]'],
            ['Habitat:', 'Mountainous or semi-open landscapes (Simulation of the natural environment) '],
            ['General Information:', 'Eagles choose a mate for life. They build large and strong nests, using branches. They lay two eggs each. While the female incubates them, the male takes care of her feeding. The hatched offspring can be seen immediately, and are covered with down. The nature of the predator forces the chicks from a young age to fight for their survival. Often one can observe the larger chick trying to push the younger brother out of the nest. Sometimes it may even kill it by fighting for food. In cases where there is enough food, several chicks grow in the nests.'],
            ['Physical features and characteristics:', 'The eagle is a bird of prey in the hawk family. It is one of the largest birds. The body length of an adult bird varies from 73 to 89 cm, with long wings up to 2.5 m in wingspan, a short tail and strong paws. The massive beak and sharp claws are the main weapons of this raptor.', 'Excellent vision allows the eagle to spot a mouse, snake, or lizard from a great height. The eyeball is large and occupies a lot of space in the skull, so eye mobility is low, but the well-developed neck makes up for this disadvantage. Eagles use their hearing more for communication than for hunting. The sense of smell is poorly developed.'],
            ['Lifestyle and reproduction:', 'Eagles choose a mate for life. They build large and strong nests, using branches. They lay two eggs each. While the female incubates them, the male takes care of her feeding. The hatched offspring can be seen immediately, and are covered with down. The nature of the predator forces the chicks from a young age to fight for their survival. Often one can observe the larger chick trying to push the younger brother out of the nest. Sometimes it may even kill it by fighting for food. In cases where there is enough food, several chicks grow in the nests.'],
            ['Habitat:', 'They can be found in the forests, tundras, steppes, and even deserts of Eurasia, North America, and Africa.'],
            ['Diet:', 'They usually hunt alone. The eagle may hover for a long time at a high altitude, looking for prey, or sit on an elevated position and observe the surroundings in search of prey. As a rule, only killed prey goes as food, carrion rarely makes it into their diet. It all depends on the type of bird. It can be both insects and large mammals. At the moment of attack, the eagle sharply lowers down, grabs the victim with its paws and strikes it with its beak. The stunned creature is no longer able to resist.'],
        ]
    }
}
